[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Dealer Docs"
authors = [{name = "bahana", email = "bahana@mail.com"}]
dynamic = ["version", "description"]
